# -*- coding: utf-8 -*-
"""neetcode.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AE9sEHXRiXRSW_jUmyvtcuRIJDIH7gvP

Two sums
"""

nums = [4,5,6,3,5,8]
target = 10

for i in range(len(nums)):

  for j in range(i+1, len(nums)):
    if nums[i] + nums[j] == target:
      print(i, j)

nums = [4,5,6,3,5,8]
target = 10
visitado = []

for i in range(len(nums)):
  visitado.append(nums[i])
  faltante = target - nums[i]
  if (faltante in visitado) and (faltante != nums[i] ) :
    print(nums[i], faltante)

nums = [4,5,6,3,5,8]
target = 10

vistos = {}

for i in range(len(nums)):
  actual = nums[i]
  faltante = target - actual
  if faltante in vistos:
    print("Índices:", [vistos[faltante], i])

  # Si no, guardo el número con su posición
  vistos[actual] = i

#prueba de hash
nums = [4,5,6,3,5,8]
target = 10

vistos = {}

for i in range(len(nums)):
  actual = nums[i]
  vistos[actual] = i
  print(vistos)

nums = [4,5,6,3,5,8]
target = 10



def ordenar(nums):
  numeros = []   # (valor, índice original)
  n = len(nums)

  for i in range(n):
    numeros.append((nums[i], i))

  for _ in range(n):
    for i in range(n-1):
      if numeros[i] > numeros[i + 1]:
        # Intercambiar numeros[i],numeros[i + 1] = numeros[i + 1], numeros[i]
        t = numeros[i]
        numeros[i] = numeros[i + 1]
        numeros[i + 1] = t
  nums= numeros
  return nums


new_nums = ordenar(nums)



def two_pointers(arreglo,t):

  l = 0  #indices iniciales
  r = len(arreglo) - 1


  while l < r :
    valor_l = arreglo[l][0]
    valor_r = arreglo[r][0]

    if valor_l + valor_r > t : #la suma es grande
      r = r - 1

    elif valor_l + valor_r < t :
      l = l + 1

    elif valor_l + valor_r == t: #hay solucion
      print(valor_l, valor_r)
      break

two_pointers(new_nums,target)

nums = [4,5,6,3,5,8]
target = 10



def ordenar(nums):
  numeros = []   # (valor, índice original)
  n = len(nums)

  for i in range(n):
    numeros.append((nums[i], i))

  for _ in range(n):
    for i in range(n-1):
      if numeros[i] > numeros[i + 1]:
        # Intercambiar numeros[i],numeros[i + 1] = numeros[i + 1], numeros[i]
        t = numeros[i]
        numeros[i] = numeros[i + 1]
        numeros[i + 1] = t
  nums= numeros
  return nums


new_nums = ordenar(nums)



def two_pointers(arreglo,t):

  l = 0  #indices iniciales
  r = len(arreglo) - 1


  while l < r :
    valor_l = arreglo[l][0]
    valor_r = arreglo[r][0]

    if valor_l + valor_r > t : #la suma es grande
      r = r - 1

    elif valor_l + valor_r < t :
      l = l + 1

    elif valor_l + valor_r == t: #hay solucion
      print(valor_l, valor_r)
      r = r - 1
      l = l + 1

two_pointers(new_nums,target)

"""3 sum"""

nums = [2, 7, 4, 0, 9, 5, 1, 3]
target = 6

for i in range(len(nums)):
    for j in range(i+1, len(nums)):
        for k in range(j+1, len(nums)):
            if nums[i] + nums[j] + nums[k] == target:
                print(nums[i], nums[j], nums[k])

nums = [2, 7, 4, 0, 9, 5, 1, 3]
target = 6

for i in range(len(nums)):
  vistos = {}
  temp_target = target - nums[i]
  for j in range(i+1, len(nums)):
     faltante = temp_target - nums[j]
     if faltante in vistos:
      print("Índices:", [i, vistos[faltante], j])
      print("valores:", [nums[i],nums[vistos[faltante]] , nums[j]])


     vistos[nums[j]] = j

nums = [2, 7, 4, 0, 9, 5, 1, 3]
target = 6

for i in range(len(nums)):
  vistos = {}
  temp_target = target - nums[i]
  for j in range(i+1, len(nums)):
    vistos[j] = nums[j]
    print(vistos)